apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "postgresRclone.secret.superuser.password" . }}
  labels:
    {{- include "postgresRclone.labels" . | nindent 4 }}
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.password | b64enc | quote }}

---

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "postgresRclone.secret.rclone.conf" . }}
  labels:
    {{- include "postgresRclone.labels" . | nindent 4 }}
data:
  rcloneConf: {{ .Values.rclone.conf | b64enc | quote }}
